version: "3"

services:
    web1:
        image: php:8.2.15-apache
        container_name: web1
        volumes:
          - ./web_1:/var/www/html
        ports:
          - "8401:80"
        working_dir: /var/www/html
    web2:
        image: php:8.2.15-apache
        container_name: web2
        volumes:
          - ./web_2:/var/www/html
        ports:
          - "8402:80"
        working_dir: /var/www/html
    web3:
        image: php:8.2.15-apache
        container_name: web3
        volumes:
          - ./web_3:/var/www/html
        ports:
          - "8403:80"
        working_dir: /var/www/html
